//Generated by webfiles.py

//8 file(s) :
//  /term.html
//     size : 1246 bytes
//     content_type : text/html
//  /favicon.ico
//     size : 2954 bytes
//     content_type : image/vnd.microsoft.icon
//  /index.html
//     size : 1246 bytes
//     content_type : text/html
//  /styles/index.css
//     size : 1300 bytes
//     content_type : text/css
//  /styles/term.css
//     size : 1300 bytes
//     content_type : text/css
//  /scripts/term.js
//     size : 3512 bytes
//     content_type : application/javascript
//  /icons/greenArrow.png
//     size : 413 bytes
//     content_type : image/png
//  /icons/redArrow.png
//     size : 406 bytes
//     content_type : image/png

#ifndef WiFiTerm_webfiles_h
#define WiFiTerm_webfiles_h

#if defined(ESP32)
  #include <WebServer.h>
#elif defined(ESP8266)
  #include <ESP8266WebServer.h>
  #define WebServer ESP8266WebServer
#endif

class WiFiTerm_webfiles_c
{
  public :
    WiFiTerm_webfiles_c();

    void begin(WebServer &webServer);
    void activateFavicon(); //must be specificly activated

    WebServer *server;

  private :
    static void send_webfiles_term_html();
    static void send_webfiles_favicon_ico();
    static void send_webfiles_index_html();
    static void send_webfiles_styles_index_css();
    static void send_webfiles_styles_term_css();
    static void send_webfiles_scripts_term_js();
    static void send_webfiles_icons_greenArrow_png();
    static void send_webfiles_icons_redArrow_png();
};

extern WiFiTerm_webfiles_c WiFiTerm_webfiles;

extern const char webfiles_term_html_path_P[];
extern const char webfiles_favicon_ico_path_P[];
extern const char webfiles_index_html_path_P[];
extern const char webfiles_styles_index_css_path_P[];
extern const char webfiles_styles_term_css_path_P[];
extern const char webfiles_scripts_term_js_path_P[];
extern const char webfiles_icons_greenArrow_png_path_P[];
extern const char webfiles_icons_redArrow_png_path_P[];

#endif

